### ISSUE TITLE
As a user, I want to specify the time of the task's deadline

### ISSUE THREAD

**Issue by limmlingg** [CS2103JAN2017-W09-B4/main#41]
...so that I can manage my tasks in more detail.

**Comment by limmlingg** [comment]
Also makes a lot more sense for implementing reminders ([Issue #12](https://github.com/CS2103JAN2017-W09-B4/main/issues/12))

**Comment by dylansyj** [comment]
@limmlingg Do you wanna work on this? if not i can work on it

**Comment by limmlingg** [comment]
I can work on it.
