### ISSUE TITLE
Developer Guide issues

### ISSUE THREAD

**Issue by eevyern** [CS2103JAN2017-W09-B4/main#46]
no need to change logic diagram; unless you refer to certain methods in the main body of the text <br>
might want to mention 'delete' <br>

UI needs to change from addressbook to tasklist --> also has 3 types of the tasks; what is the relationship between them? seperate classes? inherits from one class?

model component needs a lot of change <br>
storage as well - both need changes from addressbook to tasklist

pay attention to high priority user stories

product survey

**Comment by limmlingg** [comment]
Whoops, didn't mean to close the issue. Developer Guide still needs to be fixed.
