### ISSUE TITLE
The plan over the 4 days ( 6th to 9th April )

### ISSUE THREAD

**Issue by dylansyj** [CS2103JAN2017-W09-B4/main#89]
Thursday - UI + Bugs
Friday - Features + Bugs
Sat - JUnit + Dev + User Guide + Sample Data + Test Script
Sun - Buffer time

**Comment by dylansyj** [comment]
Thursday - 
1) Create a new list for overdue tasks.
2) Create a wrapper class for the natty (cuz the prof broke it).

Friday -
1) JUnit tests and unresolved bugs
2) Work on SE Principles

Saturday  -
1) As stated above

**Comment by ghost** [comment]
Thursday - 
1) Improve Near Match Search
2) Upcoming
3) Overdue & FindPriority Command

Friday - 
1) Feature + JUnit

Saturday - 
1) As stated above

**Comment by eevyern** [comment]
Thursday - 
1) Ignore cases of all commands
2) Delete subsets
3) JUnits

Friday -
1) Fix any loose features 
2) JUnits

Saturday -
1) As stated above

**Comment by limmlingg** [comment]
Thursday - 
1) CSS
2) absolute path for save

Friday - 
1) Reminders
2) JUnit

Sat - 
1) As stated above
